name: "Create Pull Request" # WorkFlow 명
on:
  push:
    branches:
      - feature/*

jobs:
  create-pr-on-push:  # 실행될 jobId
    runs-on: ubuntu-latest
    steps:
      - run: echo "Create PR Start"
      - uses: actions/checkout@1.0.0
      - name: Create pull request # step 이름 설정
        uses: thomaseizinger/create-pull-request@master #GitHub API
        with:
          ref: main
          GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
          head: ${{ github.ref }}
          base: release
          assignees: jiseob@stockeeper.co
          title: ${{ github.event.head_commit.message }}
      - run: echo "Create PR END"
