name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create pull request
      uses: thomaseizinger/create-pull-request@develop
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
        head: ${{ github.ref }}
        base: develop
        title: "An automatically created PR!"
