name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: shin-jiseob/gitgub-pr-test@develop
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: develop
        title: "An automatically created PR!"
