name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create pull request
      uses: shin-jiseob/gitgub-pr-test
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PULL_REQUEST }}
        head: ${{ github.ref }}
        base: develop
        title: "An automatically created PR!"
